line_length:
  warning: 150
  error: 250

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

disabled_rules:
  - trailing_whitespace
  - opening_brace
  - blanket_disable_command
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - closure_spacing
  - modifier_order
  - overridden_super_call

excluded:
  - .build
  - Klausemeister.xcodeproj
  - Klausemeister/Assets.xcassets
